name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull public Docker image from GHCR
      run: docker pull ghcr.io/<repository-name>/my-app:trilinos

        # TODO: kho write script to compile FEDDLib and run tests in run-tests.sh
        # How to make FEDDLib configure script available for the build?
    - name: Run tests
      run: docker run ghcr.io/<repository-name>/my-app:trilinos ./run-tests.sh
