# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Linter

on:
  push:
  pull_request:
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "develop"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLANG_FORMAT_FILE_NAME: "clang-format"
          LINTER_RULES_PATH: ".github/config"
